In [1]:
import numpy as np

In [2]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [3]:
y=np.array([1,2,3,4])

In [4]:
y

array([1, 2, 3, 4])

In [5]:
x=[1,2,3]

In [6]:
type(x),type(y)

(list, numpy.ndarray)

In [8]:
y/2

array([0.5, 1. , 1.5, 2. ])

In [9]:
x=[1,2,3,"data science"]

In [10]:
x

[1, 2, 3, 'data science']

In [11]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [12]:
y=np.array([1,2,3,"data science"])

In [13]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [17]:
for i in range(1,10):
  print(np.random.randint(0,10))

4
2
7
7
2
2
0
1
0


In [23]:
np.random.randint(0,10,(5,5))

array([[3, 0, 0, 8, 1],
       [5, 8, 5, 4, 4],
       [6, 3, 3, 6, 9],
       [6, 8, 4, 1, 7],
       [9, 8, 3, 7, 2]])

In [24]:
data=np.random.randint(0,100,(5,5))

In [25]:
data

array([[93, 59, 51, 88, 49],
       [34, 81, 13, 65, 61],
       [ 3,  8, 92, 60, 77],
       [76, 27,  1, 70, 99],
       [68, 19, 29, 91, 63]])

In [26]:
data[0:3,4:5]

array([[49],
       [61],
       [77]])

In [28]:
data=np.random.randint(0,10,(5,5))

In [29]:
data

array([[4, 1, 5, 4, 8],
       [5, 0, 5, 0, 4],
       [4, 5, 2, 2, 1],
       [7, 8, 5, 8, 3],
       [5, 8, 2, 3, 1]])

In [30]:
data[0:2,1:4]

array([[1, 5, 4],
       [0, 5, 0]])

In [31]:
data[1:3,2:4]

array([[5, 0],
       [2, 2]])

In [32]:
data[0:3,1:4]

array([[1, 5, 4],
       [0, 5, 0],
       [5, 2, 2]])

In [33]:
data[-1:-2,-2:-3]

array([], shape=(0, 0), dtype=int64)

In [34]:
data[0,:]

array([4, 1, 5, 4, 8])

In [36]:
data.shape

(5, 5)

In [37]:
data.size

25

In [38]:
data.T

array([[4, 5, 4, 7, 5],
       [1, 0, 5, 8, 8],
       [5, 5, 2, 5, 2],
       [4, 0, 2, 8, 3],
       [8, 4, 1, 3, 1]])

In [39]:
data

array([[4, 1, 5, 4, 8],
       [5, 0, 5, 0, 4],
       [4, 5, 2, 2, 1],
       [7, 8, 5, 8, 3],
       [5, 8, 2, 3, 1]])

In [40]:
x=2

In [41]:
data*2

array([[ 8,  2, 10,  8, 16],
       [10,  0, 10,  0,  8],
       [ 8, 10,  4,  4,  2],
       [14, 16, 10, 16,  6],
       [10, 16,  4,  6,  2]])

In [42]:
data**2

array([[16,  1, 25, 16, 64],
       [25,  0, 25,  0, 16],
       [16, 25,  4,  4,  1],
       [49, 64, 25, 64,  9],
       [25, 64,  4,  9,  1]])

In [44]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [47]:
x

array([[0, 6, 7],
       [9, 8, 4],
       [0, 5, 1]])

In [48]:
y

array([[6, 6, 2],
       [1, 7, 9],
       [5, 3, 4]])

In [49]:
np.add(x,2)

array([[ 2,  8,  9],
       [11, 10,  6],
       [ 2,  7,  3]])

In [50]:
np.multiply(x,2)

array([[ 0, 12, 14],
       [18, 16,  8],
       [ 0, 10,  2]])

In [51]:
np.divide(x,2)

array([[0. , 3. , 3.5],
       [4.5, 4. , 2. ],
       [0. , 2.5, 0.5]])

In [52]:
np.floor_divide(x,2)

array([[0, 3, 3],
       [4, 4, 2],
       [0, 2, 0]])

In [53]:
np.exp(x)

array([[1.00000000e+00, 4.03428793e+02, 1.09663316e+03],
       [8.10308393e+03, 2.98095799e+03, 5.45981500e+01],
       [1.00000000e+00, 1.48413159e+02, 2.71828183e+00]])

In [54]:
np.pow(x,2)

array([[ 0, 36, 49],
       [81, 64, 16],
       [ 0, 25,  1]])

In [57]:
np.random.randn(1300,1300).std()

np.float64(1.001006529024281)