In [1]:
import numpy as np

In [6]:
data=np.random.randint(0,10,(4,4))

In [7]:
data

array([[8, 4, 3, 1],
       [1, 5, 7, 9],
       [9, 1, 7, 3],
       [8, 0, 0, 1]])

In [8]:
data.sum()

np.int64(67)

In [9]:
data.sum(axis=0)

array([26, 10, 17, 14])

In [10]:
data.sum(axis=1)

array([16, 22, 20,  9])

In [11]:
data.max()

np.int64(9)

In [12]:
data.min()

np.int64(0)

In [14]:
data.argmax()

np.int64(7)

In [16]:
data.argmin()

np.int64(13)

In [17]:
data.max(axis=0)

array([9, 5, 7, 9])

In [18]:
data.argmax(axis=1)

array([0, 3, 0, 0])

In [19]:
data=np.random.randint(0,100,(10,5))

In [20]:
data

array([[17, 95, 65, 16, 89],
       [30, 94, 87,  4, 64],
       [27, 37, 44, 94, 51],
       [ 2, 84, 51, 86, 91],
       [10, 67, 15, 72, 58],
       [73, 19, 39, 55, 28],
       [36, 91, 88, 13, 30],
       [83, 48, 44, 82, 99],
       [52, 60, 11, 69,  2],
       [ 7, 38,  4, 70, 99]])

In [21]:
data.sum()

np.int64(2590)

In [22]:
data.sum(axis=0)

array([337, 633, 448, 561, 611])

In [23]:
data.argmax(axis=1)

array([1, 1, 3, 4, 3, 0, 1, 4, 3, 4])

In [24]:
data.max(axis=1).sum()

np.int64(877)

In [28]:
#to get only  selected  column and row
data[0:7,:]

array([[17, 95, 65, 16, 89],
       [30, 94, 87,  4, 64],
       [27, 37, 44, 94, 51],
       [ 2, 84, 51, 86, 91],
       [10, 67, 15, 72, 58],
       [73, 19, 39, 55, 28],
       [36, 91, 88, 13, 30]])

In [30]:
data[0:7,:].sum()

np.int64(1822)

In [31]:
data.sum(axis=0)[:7]

array([337, 633, 448, 561, 611])

In [32]:
data.sum(axis=0)[0:7].sum()

np.int64(2590)

In [33]:
data=np.random.randint(0,10,10)

In [34]:
data

array([1, 8, 4, 8, 8, 3, 9, 9, 0, 5])

In [ ]:
np.mean()